feat: support 2fa in the cf tools ui
SAP/cloud-foundry-tools pull request #224
Opened 2022-06-07 16:06 UTC by NetaMolcho

2022-06-26 13:01 UTC, alex-gilin requested changes
- remove all files that met 'packages/backend/resources/web/*' condition - they are generated resources
- remove packages/frontend/public/generator.png
- remove packages/frontend/src/assets/css/globalStyles.css

2022-06-26 14:05 UTC, alex-gilin commented on packages/backend/package.json
> +    "copy:test-resources": "cp -r ./tests/resources ./out/tests/resources",
```suggestion
    "copy:test-resources": "shx cp -r ./tests/resources ./out/tests/resources",
```

2022-06-26 14:13 UTC, alex-gilin commented on packages/backend/package.json
> +    "show-out-debug": "ls -LR -a ./out",
```suggestion
    "show-out-debug": "shx ls -la ./out",
```

2022-06-27 12:57 UTC, veredcon commented on .circleci/config.yml
> +      # - build-and-test-node18
removed

2022-06-27 12:57 UTC, veredcon commented on .eslintrc.js
> +    // TODO "eslint-comments/require-description": ["error", { ignore: [] }],
removed

2022-06-27 12:57 UTC, veredcon commented on .npmignore
> +generator-foodq
removed .npmignore

2022-06-27 12:57 UTC, veredcon commented on .vscode/launch.json
> +    },
done

2022-06-27 12:57 UTC, veredcon commented on .vscode/launch.json
> +    },
right - removed

2022-06-27 12:57 UTC, veredcon commented on .vscode/launch.json
> +    },
done

2022-06-27 12:57 UTC, veredcon commented on lerna.json
> +  "version": "0.0.1"
done

2022-06-27 12:57 UTC, veredcon commented on packages/backend/package.json
> +    "build-all": "npm run frontend:copy && npm run webpack-dev",
removed "build-all"

2022-06-27 12:57 UTC, veredcon commented on packages/backend/package.json
> +    "copy:test-resources": "cp -r ./tests/resources ./out/tests/resources",
done

2022-06-28 13:14 UTC, alex-gilin approved these changes

2022-06-28 13:14 UTC, merged